/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }
    
    class CuentaBancaria {
    private double saldo;

    public CuentaBancaria() {
        this.saldo = 0.0;
    }

    public double consultarSaldo() {
        return saldo;
    }

    public void depositar(double cantidad) {
        saldo += cantidad;
        JOptionPane.showMessageDialog(null, "Se depositaron " + cantidad + " unidades. Saldo actual: " + saldo);
    }

    public void retirar(double cantidad) {
        if (cantidad > saldo) {
            JOptionPane.showMessageDialog(null, "Fondos insuficientes.");
        } else {
            saldo -= cantidad;
            JOptionPane.showMessageDialog(null, "Se retiraron " + cantidad + " unidades. Saldo actual: " + saldo);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        texto1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transca1.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 220, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/59588435-diseño-plano-paisaje-urbano-ilustración.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 430));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("       bienvenido al menu de opciones introduzca el numero");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 6, 330, 40));

        jLabel4.setText("1. depositar dinero y sacar dinero");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel5.setText("2. ver horarios y rutas");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel7.setText("3. historial de gastos");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel8.setText("4. salir");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        panel1.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 90, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Convertir la entrada a un número entero
        String numero1 = texto1.getText();
        int numero = Integer.parseInt(numero1);

        // Evaluar el número y mostrar un mensaje correspondiente
        switch (numero) {
            case 1:
         CuentaBancaria cuenta = new CuentaBancaria();

        while (true) {
            String opcionStr = JOptionPane.showInputDialog(
                "1. Consultar saldo\n" +
                "2. Depositar dinero\n" +
                "3. Retirar dinero\n" +
                "4. Salir\n" +
                "Seleccione una opción:"
            );

            int opcion = Integer.parseInt(opcionStr);

            switch (opcion) {
                case 1:
                    JOptionPane.showMessageDialog(null, "Saldo actual: " + cuenta.consultarSaldo());
                    break;
                case 2:
                    String depositoStr = JOptionPane.showInputDialog("Ingrese la cantidad a depositar:");
                    double deposito = Double.parseDouble(depositoStr);
                    cuenta.depositar(deposito);
                    break;
                case 3:
                    String retiroStr = JOptionPane.showInputDialog("Ingrese la cantidad a retirar:");
                    double retiro = Double.parseDouble(retiroStr);
                    cuenta.retirar(retiro);
                    break;
                case 4:
                    JOptionPane.showMessageDialog(null, "¡Hasta luego!");
                    System.exit(0);
                default:
                    JOptionPane.showMessageDialog(null, "Opción no válida. Inténtelo de nuevo.");      
            break;
            }
        }
            case 2:
            new horarios_y_rutas().setVisible(true);
            break;
            case 3:
            new historial().setVisible(true);
            break;
            case 4:
            setVisible(false);
            break;
            default:
            JOptionPane.showMessageDialog(null, "Número no válido. Por favor, ingrese un número del 1 al 5.");
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField texto1;
    // End of variables declaration//GEN-END:variables

    void setVisible(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}